# Generated by Django 4.0.1 on 2022-01-14 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=50)),
                ('submission_date', models.DateField(verbose_name='Submission Date')),
                ('follow_up_date', models.DateField(verbose_name='Follow-Up Date')),
                ('job_post_url', models.CharField(max_length=999)),
                ('description', models.CharField(max_length=256)),
                ('notes', models.CharField(max_length=256)),
                ('excitement_level', models.IntegerField()),
                ('resume_url', models.CharField(max_length=999)),
                ('cover_letter_url', models.CharField(max_length=999)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
