# Generated by Django 4.0.1 on 2022-01-15 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IP', 'Interview Prep'), ('CC', 'Coding Challenge'), ('AL', 'Algorithms'), ('DS', 'Data Structures'), ('CS', 'Cheat Sheets'), ('RT', 'Resume Tips'), ('HR', 'Hiring Resources')], default='IP', max_length=2)),
                ('title', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=999)),
                ('resource_url', models.CharField(max_length=100)),
                ('replies', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
