# Generated by Django 4.0.1 on 2022-01-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_resources_favorite_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapp',
            name='status',
            field=models.CharField(choices=[('1', 'Screening'), ('2', 'First Interview'), ('3', 'Second Interview'), ('4', 'Third Interview'), ('5', 'Received Job Offer'), ('6', 'Accepted Offer'), ('7', 'Declined Offer'), ('8', 'Rejected')], default='1', max_length=1),
        ),
    ]
